-- ============================================================================
-- CHAIWALE PLATFORM: 002_seed_menu_data.sql
-- Authentic menu data extracted from official Chaiwale physical menu board
-- Prices verified from original menu images provided by client
-- ============================================================================

-- ─── CATEGORIES ────────────────────────────────────────────────────────────
INSERT INTO menu_categories (slug, name, display_order) VALUES ('tea', 'Tea', 1) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, display_order = EXCLUDED.display_order;
INSERT INTO menu_categories (slug, name, display_order) VALUES ('breakfast', 'Breakfast', 2) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, display_order = EXCLUDED.display_order;
INSERT INTO menu_categories (slug, name, display_order) VALUES ('shakes-drinks', 'Shake/Drinks', 3) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, display_order = EXCLUDED.display_order;
INSERT INTO menu_categories (slug, name, display_order) VALUES ('lunch', 'Lunch', 4) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, display_order = EXCLUDED.display_order;
INSERT INTO menu_categories (slug, name, display_order) VALUES ('snacks', 'Snacks', 5) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, display_order = EXCLUDED.display_order;
INSERT INTO menu_categories (slug, name, display_order) VALUES ('maggie', 'Maggie', 6) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, display_order = EXCLUDED.display_order;
INSERT INTO menu_categories (slug, name, display_order) VALUES ('egg-items', 'Egg Items', 7) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, display_order = EXCLUDED.display_order;
INSERT INTO menu_categories (slug, name, display_order) VALUES ('sandwich', 'Sandwich', 8) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, display_order = EXCLUDED.display_order;
INSERT INTO menu_categories (slug, name, display_order) VALUES ('chinese', 'Chinese', 9) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, display_order = EXCLUDED.display_order;
INSERT INTO menu_categories (slug, name, display_order) VALUES ('momos', 'Momos', 10) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, display_order = EXCLUDED.display_order;
INSERT INTO menu_categories (slug, name, display_order) VALUES ('thali', 'Thali', 11) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, display_order = EXCLUDED.display_order;
INSERT INTO menu_categories (slug, name, display_order) VALUES ('moms-daawat', 'Mom''s Daawat', 12) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, display_order = EXCLUDED.display_order;

-- ─── TEA ───────────────────────────────────────────────────────────────────
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'tea'), 'green-tea', 'Green Tea', NULL, 20, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'tea'), 'tea', 'Tea', NULL, 12, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'tea'), 'chai-wale-special-milk-tea', 'Chai Wale Special Milk Tea', NULL, 25, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'tea'), 'lemon-tea', 'Lemon Tea', NULL, 15, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'tea'), 'black-coffee', 'Black Coffee', NULL, 15, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'tea'), 'coffee', 'Coffee', NULL, 30, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;

-- ─── BREAKFAST ─────────────────────────────────────────────────────────────
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'breakfast'), 'aalu-paratha', 'Aalu Paratha', NULL, 30, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'breakfast'), 'gobi-paratha', 'Gobi Paratha', NULL, 40, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'breakfast'), 'paneer-paratha', 'Paneer Paratha', NULL, 60, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'breakfast'), 'pyaz-paratha', 'Pyaz Paratha', NULL, 30, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'breakfast'), 'egg-paratha', 'Egg Paratha', NULL, 60, false, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'breakfast'), 'aalu-puri', 'Aalu Puri', NULL, 60, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'breakfast'), 'chhole-bhature', 'Chhole Bhature', NULL, 60, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;

-- ─── SHAKE / DRINKS ────────────────────────────────────────────────────────
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'shakes-drinks'), 'mango-shake', 'Mango Shake', NULL, 80, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'shakes-drinks'), 'strawberry-shake', 'Strawberry Shake', NULL, 80, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'shakes-drinks'), 'banana-shake', 'Banana Shake', NULL, 80, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'shakes-drinks'), 'oreo-shake', 'Oreo Shake', NULL, 80, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'shakes-drinks'), 'cold-coffee', 'Cold Coffee', NULL, 60, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'shakes-drinks'), 'sweet-salt-lassi', 'Sweet / Salt Lassi', NULL, 40, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'shakes-drinks'), 'sikanji', 'Sikanji', NULL, 30, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'shakes-drinks'), 'jaljeera', 'Jaljeera', NULL, 20, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;

-- ─── LUNCH ─────────────────────────────────────────────────────────────────
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'lunch'), 'shahi-paneer-chawal-half', 'Shahi Paneer Chawal (Half)', NULL, 70, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'lunch'), 'shahi-paneer-chawal-full', 'Shahi Paneer Chawal (Full)', NULL, 120, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'lunch'), 'matar-paneer-chawal-half', 'Matar Paneer Chawal (Half)', NULL, 70, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'lunch'), 'matar-paneer-chawal-full', 'Matar Paneer Chawal (Full)', NULL, 120, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'lunch'), 'yellow-dal-chawal-half', 'Yellow Dal Chawal (Half)', NULL, 40, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'lunch'), 'yellow-dal-chawal-full', 'Yellow Dal Chawal (Full)', NULL, 60, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'lunch'), 'kadhi-chawal-half', 'Kadhi Chawal (Half)', NULL, 40, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'lunch'), 'kadhi-chawal-full', 'Kadhi Chawal (Full)', NULL, 60, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'lunch'), 'rajma-chawal-half', 'Rajma Chawal (Half)', NULL, 40, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'lunch'), 'rajma-chawal-full', 'Rajma Chawal (Full)', NULL, 60, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'lunch'), 'chhole-chawal-half', 'Chhole Chawal (Half)', NULL, 40, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'lunch'), 'chhole-chawal-full', 'Chhole Chawal (Full)', NULL, 60, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;

-- ─── SNACKS ────────────────────────────────────────────────────────────────
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'snacks'), 'samosa', 'Samosa', NULL, 15, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'snacks'), 'bread-pakoda', 'Bread Pakoda', NULL, 15, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'snacks'), 'paneer-bread-pakoda', 'Paneer Bread Pakoda', NULL, 25, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'snacks'), 'bread-roll', 'Bread Roll', NULL, 50, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'snacks'), 'spring-roll', 'Spring Roll', NULL, 60, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'snacks'), 'paneer-pakoda', 'Paneer Pakoda', NULL, 60, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'snacks'), 'mix-pakoda', 'Mix Pakoda', NULL, 70, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;

-- ─── MAGGIE ────────────────────────────────────────────────────────────────
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'maggie'), 'veg-maggie', 'Veg Maggie', NULL, 50, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'maggie'), 'butter-maggie', 'Butter Maggie', NULL, 60, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'maggie'), 'butter-cheese-maggie', 'Butter Cheese Maggie', NULL, 80, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'maggie'), 'egg-maggie', 'Egg Maggie', NULL, 80, false, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;

-- ─── EGG ITEMS ─────────────────────────────────────────────────────────────
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'egg-items'), 'bread-omelette', 'Bread Omelette', NULL, 70, false, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'egg-items'), 'bread-omelette-butter', 'Bread Omelette (Butter)', NULL, 90, false, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'egg-items'), 'egg-bhurji-4-egg', 'Egg Bhurji (4 Egg)', NULL, 80, false, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'egg-items'), 'omelette', 'Omelette', NULL, 50, false, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'egg-items'), 'boiled-egg', 'Boiled Egg', NULL, 15, false, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;

-- ─── SANDWICH ──────────────────────────────────────────────────────────────
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'sandwich'), 'veg-sandwich', 'Veg Sandwich', NULL, 45, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'sandwich'), 'garlic-veg-cheese-sandwich', 'Garlic Veg Cheese Sandwich', NULL, 80, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'sandwich'), 'garlic-paneer-cheese-sandwich', 'Garlic Paneer Cheese Sandwich', NULL, 90, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'sandwich'), 'peanut-butter-sandwich', 'Peanut Butter Sandwich', NULL, 70, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'sandwich'), 'butter-toast', 'Butter Toast', NULL, 30, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'sandwich'), 'bun-maska', 'Bun Maska', NULL, 25, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;

-- ─── CHINESE ───────────────────────────────────────────────────────────────
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'chinese'), 'veg-noodles-half', 'Veg Noodles (Half)', NULL, 60, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'chinese'), 'veg-noodles-full', 'Veg Noodles (Full)', NULL, 90, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'chinese'), 'singapuri-noodles-half', 'Singapuri Noodles (Half)', NULL, 80, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'chinese'), 'singapuri-noodles-full', 'Singapuri Noodles (Full)', NULL, 100, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'chinese'), 'chilli-garlic-noodles-half', 'Chilli Garlic Noodles (Half)', NULL, 90, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'chinese'), 'chilli-garlic-noodles-full', 'Chilli Garlic Noodles (Full)', NULL, 120, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'chinese'), 'fried-rice-half', 'Fried Rice (Half)', NULL, 60, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'chinese'), 'fried-rice-full', 'Fried Rice (Full)', NULL, 100, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'chinese'), 'egg-fried-rice-half', 'Egg Fried Rice (Half)', NULL, 70, false, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'chinese'), 'egg-fried-rice-full', 'Egg Fried Rice (Full)', NULL, 120, false, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;

-- ─── MOMOS ─────────────────────────────────────────────────────────────────
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'momos'), 'veg-steam-momos-half', 'Veg Steam Momos (Half)', NULL, 40, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'momos'), 'veg-steam-momos-full', 'Veg Steam Momos (Full)', NULL, 60, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'momos'), 'veg-fried-momos-half', 'Veg Fried Momos (Half)', NULL, 60, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'momos'), 'veg-fried-momos-full', 'Veg Fried Momos (Full)', NULL, 80, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'momos'), 'veg-gravy-momos-half', 'Veg Gravy Momos (Half)', NULL, 80, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'momos'), 'veg-gravy-momos-full', 'Veg Gravy Momos (Full)', NULL, 100, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'momos'), 'chicken-steam-momos-half', 'Chicken Steam Momos (Half)', NULL, 60, false, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'momos'), 'chicken-steam-momos-full', 'Chicken Steam Momos (Full)', NULL, 80, false, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'momos'), 'chicken-fried-momos-half', 'Chicken Fried Momos (Half)', NULL, 80, false, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'momos'), 'chicken-fried-momos-full', 'Chicken Fried Momos (Full)', NULL, 100, false, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'momos'), 'chicken-gravy-momos-half', 'Chicken Gravy Momos (Half)', NULL, 100, false, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'momos'), 'chicken-gravy-momos-full', 'Chicken Gravy Momos (Full)', NULL, 120, false, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;

-- ─── THALI ─────────────────────────────────────────────────────────────────
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'thali'), 'veg-thali', 'Veg Thali', '3 Sabzi + 4 Tawa Roti + Rice + Salad + Achar + Sweet', 99, true, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, description = EXCLUDED.description, category_id = EXCLUDED.category_id;

-- ─── MOM'S DAAWAT — Chicken & Mutton Specialities ─────────────────────────
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'moms-daawat'), 'authentic-bihari-chicken-half', 'Authentic Bihari Chicken (Half)', 'Slow cooked in sealed clay handi with whole garlic bulbs and authentic Bihari spices.', 400, false, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'moms-daawat'), 'authentic-bihari-chicken-full', 'Authentic Bihari Chicken (Full)', 'Slow cooked in sealed clay handi with whole garlic bulbs and authentic Bihari spices.', 800, false, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'moms-daawat'), 'cream-chicken-half', 'Cream Chicken (Half)', 'Rich creamy chicken cooked in cashew and fresh cream gravy.', 480, false, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'moms-daawat'), 'cream-chicken-full', 'Cream Chicken (Full)', 'Rich creamy chicken cooked in cashew and fresh cream gravy.', 900, false, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'moms-daawat'), 'lemon-chicken-half', 'Lemon Chicken (Half)', 'Tangy lemon marinated chicken with fresh herbs.', 380, false, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'moms-daawat'), 'lemon-chicken-full', 'Lemon Chicken (Full)', 'Tangy lemon marinated chicken with fresh herbs.', 700, false, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'moms-daawat'), 'authentic-bihari-mutton-half', 'Authentic Bihari Mutton (Half)', 'Slow cooked tender mutton in authentic Bihari style with whole spices.', 700, false, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'moms-daawat'), 'authentic-bihari-mutton-full', 'Authentic Bihari Mutton (Full)', 'Slow cooked tender mutton in authentic Bihari style with whole spices.', 1400, false, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'moms-daawat'), 'champaran-chicken-half', 'Champaran Chicken (Half)', 'Champaran ahuna style slow-cooked chicken in sealed pot.', 500, false, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'moms-daawat'), 'champaran-chicken-full', 'Champaran Chicken (Full)', 'Champaran ahuna style slow-cooked chicken in sealed pot.', 900, false, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'moms-daawat'), 'champaran-mutton-half', 'Champaran Mutton (Half)', 'Champaran ahuna style slow-cooked mutton in sealed pot.', 800, false, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'moms-daawat'), 'champaran-mutton-full', 'Champaran Mutton (Full)', 'Champaran ahuna style slow-cooked mutton in sealed pot.', 1500, false, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'moms-daawat'), 'chicken-pakoda-half', 'Chicken Pakoda (Half)', 'Crispy golden fried chicken pakoda.', 250, false, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'moms-daawat'), 'chicken-pakoda-full', 'Chicken Pakoda (Full)', 'Crispy golden fried chicken pakoda.', 400, false, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'moms-daawat'), 'butter-chicken-half', 'Butter Chicken (Half)', 'Classic creamy tomato butter chicken.', 450, false, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'moms-daawat'), 'butter-chicken-full', 'Butter Chicken (Full)', 'Classic creamy tomato butter chicken.', 800, false, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'moms-daawat'), 'dragon-chicken-half', 'Dragon Chicken (Half)', 'Spicy Indo-Chinese dragon chicken.', 300, false, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'moms-daawat'), 'dragon-chicken-full', 'Dragon Chicken (Full)', 'Spicy Indo-Chinese dragon chicken.', 500, false, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'moms-daawat'), 'chatpata-chicken-half', 'Chatpata Chicken (Half)', 'Tangy spicy chatpata chicken preparation.', 300, false, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'moms-daawat'), 'chatpata-chicken-full', 'Chatpata Chicken (Full)', 'Tangy spicy chatpata chicken preparation.', 500, false, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'moms-daawat'), 'chicken-seekh-masala-half', 'Chicken Seekh Masala (Half)', 'Juicy seekh kabab in masala gravy.', 200, false, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;
INSERT INTO menu_items (category_id, slug, name, description, base_price, is_veg, image_path) VALUES ((SELECT id FROM menu_categories WHERE slug = 'moms-daawat'), 'chicken-seekh-masala-full', 'Chicken Seekh Masala (Full)', 'Juicy seekh kabab in masala gravy.', 400, false, NULL) ON CONFLICT (slug) DO UPDATE SET base_price = EXCLUDED.base_price, name = EXCLUDED.name, category_id = EXCLUDED.category_id;