export const SEED_CATEGORIES = [
  {
    "id": "tea",
    "slug": "tea",
    "name": "Tea",
    "display_order": 1,
    "is_active": true
  },
  {
    "id": "breakfast",
    "slug": "breakfast",
    "name": "Breakfast",
    "display_order": 2,
    "is_active": true
  },
  {
    "id": "shakes-drinks",
    "slug": "shakes-drinks",
    "name": "Shake/Drinks",
    "display_order": 3,
    "is_active": true
  },
  {
    "id": "lunch",
    "slug": "lunch",
    "name": "Lunch",
    "display_order": 4,
    "is_active": true
  },
  {
    "id": "snacks",
    "slug": "snacks",
    "name": "Snacks",
    "display_order": 5,
    "is_active": true
  },
  {
    "id": "maggie",
    "slug": "maggie",
    "name": "Maggie",
    "display_order": 6,
    "is_active": true
  },
  {
    "id": "egg-items",
    "slug": "egg-items",
    "name": "Egg Items",
    "display_order": 7,
    "is_active": true
  },
  {
    "id": "sandwich",
    "slug": "sandwich",
    "name": "Sandwich",
    "display_order": 8,
    "is_active": true
  },
  {
    "id": "chinese",
    "slug": "chinese",
    "name": "Chinese",
    "display_order": 9,
    "is_active": true
  },
  {
    "id": "momos",
    "slug": "momos",
    "name": "Momos",
    "display_order": 10,
    "is_active": true
  },
  {
    "id": "thali",
    "slug": "thali",
    "name": "Thali",
    "display_order": 11,
    "is_active": true
  }
];

export const SEED_ITEMS = [
  {
    "id": "green-tea",
    "category_id": "tea",
    "slug": "green-tea",
    "name": "Green Tea",
    "description": null,
    "base_price": 30,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "tea",
    "category_id": "tea",
    "slug": "tea",
    "name": "Tea",
    "description": null,
    "base_price": 15,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "chai-wale-special-milk-tea",
    "category_id": "tea",
    "slug": "chai-wale-special-milk-tea",
    "name": "Chai Wale Special Milk Tea",
    "description": null,
    "base_price": 30,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "lemon-tea",
    "category_id": "tea",
    "slug": "lemon-tea",
    "name": "Lemon Tea",
    "description": null,
    "base_price": 20,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "black-coffee",
    "category_id": "tea",
    "slug": "black-coffee",
    "name": "Black Coffee",
    "description": null,
    "base_price": 20,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "coffee",
    "category_id": "tea",
    "slug": "coffee",
    "name": "Coffee",
    "description": null,
    "base_price": 40,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "aalu-paratha",
    "category_id": "breakfast",
    "slug": "aalu-paratha",
    "name": "Aalu Paratha",
    "description": null,
    "base_price": 40,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "gobi-paratha",
    "category_id": "breakfast",
    "slug": "gobi-paratha",
    "name": "Gobi Paratha",
    "description": null,
    "base_price": 50,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "paneer-paratha",
    "category_id": "breakfast",
    "slug": "paneer-paratha",
    "name": "Paneer Paratha",
    "description": null,
    "base_price": 60,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "pyaz-paratha",
    "category_id": "breakfast",
    "slug": "pyaz-paratha",
    "name": "Pyaz Paratha",
    "description": null,
    "base_price": 40,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "egg-paratha",
    "category_id": "breakfast",
    "slug": "egg-paratha",
    "name": "Egg Paratha",
    "description": null,
    "base_price": 70,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "aalu-puri",
    "category_id": "breakfast",
    "slug": "aalu-puri",
    "name": "Aalu Puri",
    "description": null,
    "base_price": 70,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "chhole-bhature",
    "category_id": "breakfast",
    "slug": "chhole-bhature",
    "name": "Chhole Bhature",
    "description": null,
    "base_price": 80,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "virgin-mojito",
    "category_id": "shakes-drinks",
    "slug": "virgin-mojito",
    "name": "Virgin Mojito",
    "description": null,
    "base_price": 80,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "mango-shake",
    "category_id": "shakes-drinks",
    "slug": "mango-shake",
    "name": "Mango Shake",
    "description": null,
    "base_price": 80,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "strawberry-shake",
    "category_id": "shakes-drinks",
    "slug": "strawberry-shake",
    "name": "Strawberry Shake",
    "description": null,
    "base_price": 80,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "banana-shake",
    "category_id": "shakes-drinks",
    "slug": "banana-shake",
    "name": "Banana Shake",
    "description": null,
    "base_price": 80,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "oreo-shake",
    "category_id": "shakes-drinks",
    "slug": "oreo-shake",
    "name": "Oreo Shake",
    "description": null,
    "base_price": 80,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "cold-coffee",
    "category_id": "shakes-drinks",
    "slug": "cold-coffee",
    "name": "Cold Coffee",
    "description": null,
    "base_price": 80,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "sweet-lassi",
    "category_id": "shakes-drinks",
    "slug": "sweet-lassi",
    "name": "Sweet Lassi",
    "description": null,
    "base_price": 60,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "salt-lassi",
    "category_id": "shakes-drinks",
    "slug": "salt-lassi",
    "name": "Salt Lassi",
    "description": null,
    "base_price": 60,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "sikanji",
    "category_id": "shakes-drinks",
    "slug": "sikanji",
    "name": "Sikanji",
    "description": null,
    "base_price": 50,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "jaljeera",
    "category_id": "shakes-drinks",
    "slug": "jaljeera",
    "name": "Jaljeera",
    "description": null,
    "base_price": 50,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "shahi-paneer-chawal-half",
    "category_id": "lunch",
    "slug": "shahi-paneer-chawal-half",
    "name": "Shahi Paneer Chawal (Half)",
    "description": null,
    "base_price": 70,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "matar-paneer-chawal-half",
    "category_id": "lunch",
    "slug": "matar-paneer-chawal-half",
    "name": "Matar Paneer Chawal (Half)",
    "description": null,
    "base_price": 70,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "yellow-dal-chawal-half",
    "category_id": "lunch",
    "slug": "yellow-dal-chawal-half",
    "name": "Yellow Dal Chawal (Half)",
    "description": null,
    "base_price": 50,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "kadhi-chawal-half",
    "category_id": "lunch",
    "slug": "kadhi-chawal-half",
    "name": "Kadhi Chawal (Half)",
    "description": null,
    "base_price": 40,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "rajma-chawal-half",
    "category_id": "lunch",
    "slug": "rajma-chawal-half",
    "name": "Rajma Chawal (Half)",
    "description": null,
    "base_price": 40,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "chhole-chawal-half",
    "category_id": "lunch",
    "slug": "chhole-chawal-half",
    "name": "Chhole Chawal (Half)",
    "description": null,
    "base_price": 40,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "shahi-paneer-chawal-full",
    "category_id": "lunch",
    "slug": "shahi-paneer-chawal-full",
    "name": "Shahi Paneer Chawal (Full)",
    "description": null,
    "base_price": 120,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "matar-paneer-chawal-full",
    "category_id": "lunch",
    "slug": "matar-paneer-chawal-full",
    "name": "Matar Paneer Chawal (Full)",
    "description": null,
    "base_price": 120,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "yellow-dal-chawal-full",
    "category_id": "lunch",
    "slug": "yellow-dal-chawal-full",
    "name": "Yellow Dal Chawal (Full)",
    "description": null,
    "base_price": 80,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "kadhi-chawal-full",
    "category_id": "lunch",
    "slug": "kadhi-chawal-full",
    "name": "Kadhi Chawal (Full)",
    "description": null,
    "base_price": 70,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "rajma-chawal-full",
    "category_id": "lunch",
    "slug": "rajma-chawal-full",
    "name": "Rajma Chawal (Full)",
    "description": null,
    "base_price": 70,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "chhole-chawal-full",
    "category_id": "lunch",
    "slug": "chhole-chawal-full",
    "name": "Chhole Chawal (Full)",
    "description": null,
    "base_price": 70,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "samosa",
    "category_id": "snacks",
    "slug": "samosa",
    "name": "Samosa",
    "description": null,
    "base_price": 20,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "bread-pakoda",
    "category_id": "snacks",
    "slug": "bread-pakoda",
    "name": "Bread Pakoda",
    "description": null,
    "base_price": 20,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "paneer-bread-pakoda",
    "category_id": "snacks",
    "slug": "paneer-bread-pakoda",
    "name": "Paneer Bread Pakoda",
    "description": null,
    "base_price": 30,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "bread-roll",
    "category_id": "snacks",
    "slug": "bread-roll",
    "name": "Bread Roll",
    "description": null,
    "base_price": 70,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "spring-roll",
    "category_id": "snacks",
    "slug": "spring-roll",
    "name": "Spring Roll",
    "description": null,
    "base_price": 60,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "paneer-pakoda",
    "category_id": "snacks",
    "slug": "paneer-pakoda",
    "name": "Paneer Pakoda",
    "description": null,
    "base_price": 70,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "mix-pakoda",
    "category_id": "snacks",
    "slug": "mix-pakoda",
    "name": "Mix Pakoda",
    "description": null,
    "base_price": 70,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "veg-maggie",
    "category_id": "maggie",
    "slug": "veg-maggie",
    "name": "Veg Maggie",
    "description": null,
    "base_price": 70,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "butter-maggie",
    "category_id": "maggie",
    "slug": "butter-maggie",
    "name": "Butter Maggie",
    "description": null,
    "base_price": 70,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "butter-cheese-maggie",
    "category_id": "maggie",
    "slug": "butter-cheese-maggie",
    "name": "Butter Cheese Maggie",
    "description": null,
    "base_price": 90,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "egg-maggie",
    "category_id": "maggie",
    "slug": "egg-maggie",
    "name": "Egg Maggie",
    "description": null,
    "base_price": 80,
    "is_veg": false,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "bread-omelette",
    "category_id": "egg-items",
    "slug": "bread-omelette",
    "name": "Bread Omelette",
    "description": null,
    "base_price": 70,
    "is_veg": false,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "bread-omelette-butter",
    "category_id": "egg-items",
    "slug": "bread-omelette-butter",
    "name": "Bread Omelette Butter",
    "description": null,
    "base_price": 90,
    "is_veg": false,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "egg-bhurji-4-egg",
    "category_id": "egg-items",
    "slug": "egg-bhurji-4-egg",
    "name": "Egg Bhurji (4 Egg)",
    "description": null,
    "base_price": 80,
    "is_veg": false,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "omelette",
    "category_id": "egg-items",
    "slug": "omelette",
    "name": "Omelette",
    "description": null,
    "base_price": 60,
    "is_veg": false,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "boiled-egg",
    "category_id": "egg-items",
    "slug": "boiled-egg",
    "name": "Boiled Egg",
    "description": null,
    "base_price": 15,
    "is_veg": false,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "veg-sandwich",
    "category_id": "sandwich",
    "slug": "veg-sandwich",
    "name": "Veg Sandwich",
    "description": null,
    "base_price": 45,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "garlic-veg-cheese-sandwich",
    "category_id": "sandwich",
    "slug": "garlic-veg-cheese-sandwich",
    "name": "Garlic Veg Cheese Sandwich",
    "description": null,
    "base_price": 80,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "garlic-paneer-cheese-sandwich",
    "category_id": "sandwich",
    "slug": "garlic-paneer-cheese-sandwich",
    "name": "Garlic Paneer Cheese Sandwich",
    "description": null,
    "base_price": 90,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "peanut-butter-sandwich",
    "category_id": "sandwich",
    "slug": "peanut-butter-sandwich",
    "name": "Peanut Butter Sandwich",
    "description": null,
    "base_price": 70,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "butter-toast",
    "category_id": "sandwich",
    "slug": "butter-toast",
    "name": "Butter Toast",
    "description": null,
    "base_price": 40,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "bun-maska",
    "category_id": "sandwich",
    "slug": "bun-maska",
    "name": "Bun Maska",
    "description": null,
    "base_price": 40,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "veg-noodles-half",
    "category_id": "chinese",
    "slug": "veg-noodles-half",
    "name": "Veg Noodles (Half)",
    "description": null,
    "base_price": 70,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "singapuri-noodles-half",
    "category_id": "chinese",
    "slug": "singapuri-noodles-half",
    "name": "Singapuri Noodles  (Half)",
    "description": null,
    "base_price": 80,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "chilli-garlic-noodles-half",
    "category_id": "chinese",
    "slug": "chilli-garlic-noodles-half",
    "name": "Chilli Garlic Noodles  (Half)",
    "description": null,
    "base_price": 90,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "fried-rice-half",
    "category_id": "chinese",
    "slug": "fried-rice-half",
    "name": "Fried Rice  (Half)",
    "description": null,
    "base_price": 60,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "egg-fried-rice-half",
    "category_id": "chinese",
    "slug": "egg-fried-rice-half",
    "name": "Egg Fried Rice  (Half)",
    "description": null,
    "base_price": 70,
    "is_veg": false,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "veg-noodles-full",
    "category_id": "chinese",
    "slug": "veg-noodles-full",
    "name": "Veg Noodles (Full)",
    "description": null,
    "base_price": 120,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "singapuri-noodles-full",
    "category_id": "chinese",
    "slug": "singapuri-noodles-full",
    "name": "Singapuri Noodles  (Full)",
    "description": null,
    "base_price": 150,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "chilli-garlic-noodles-full",
    "category_id": "chinese",
    "slug": "chilli-garlic-noodles-full",
    "name": "Chilli Garlic Noodles  (Full)",
    "description": null,
    "base_price": 170,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "fried-rice-full",
    "category_id": "chinese",
    "slug": "fried-rice-full",
    "name": "Fried Rice  (Full)",
    "description": null,
    "base_price": 110,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "egg-fried-rice-full",
    "category_id": "chinese",
    "slug": "egg-fried-rice-full",
    "name": "Egg Fried Rice  (Full)",
    "description": null,
    "base_price": 130,
    "is_veg": false,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "veg-steam-momos-half",
    "category_id": "momos",
    "slug": "veg-steam-momos-half",
    "name": "Veg Steam Momos  (Half)",
    "description": null,
    "base_price": 40,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "veg-fried-momos-half",
    "category_id": "momos",
    "slug": "veg-fried-momos-half",
    "name": "Veg Fried Momos  (Half)",
    "description": null,
    "base_price": 60,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "veg-gravy-momos-half",
    "category_id": "momos",
    "slug": "veg-gravy-momos-half",
    "name": "Veg Gravy Momos  (Half)",
    "description": null,
    "base_price": 70,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "chicken-steam-momos-half",
    "category_id": "momos",
    "slug": "chicken-steam-momos-half",
    "name": "Chicken Steam Momos  (Half)",
    "description": null,
    "base_price": 60,
    "is_veg": false,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "chicken-fried-momos-half",
    "category_id": "momos",
    "slug": "chicken-fried-momos-half",
    "name": "Chicken Fried Momos  (Half)",
    "description": null,
    "base_price": 80,
    "is_veg": false,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "chicken-gravy-momos-half",
    "category_id": "momos",
    "slug": "chicken-gravy-momos-half",
    "name": "Chicken Gravy Momos  (Half)",
    "description": null,
    "base_price": 90,
    "is_veg": false,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "veg-steam-momos-full",
    "category_id": "momos",
    "slug": "veg-steam-momos-full",
    "name": "Veg Steam Momos  (Full)",
    "description": null,
    "base_price": 80,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "veg-fried-momos-full",
    "category_id": "momos",
    "slug": "veg-fried-momos-full",
    "name": "Veg Fried Momos  (Full)",
    "description": null,
    "base_price": 100,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "veg-gravy-momos-full",
    "category_id": "momos",
    "slug": "veg-gravy-momos-full",
    "name": "Veg Gravy Momos  (Full)",
    "description": null,
    "base_price": 100,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "chicken-steam-momos-full",
    "category_id": "momos",
    "slug": "chicken-steam-momos-full",
    "name": "Chicken Steam Momos  (Full)",
    "description": null,
    "base_price": 100,
    "is_veg": false,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "chicken-fried-momos-full",
    "category_id": "momos",
    "slug": "chicken-fried-momos-full",
    "name": "Chicken Fried Momos  (Full)",
    "description": null,
    "base_price": 120,
    "is_veg": false,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "chicken-gravy-momos-full",
    "category_id": "momos",
    "slug": "chicken-gravy-momos-full",
    "name": "Chicken Gravy Momos  (Full)",
    "description": null,
    "base_price": 150,
    "is_veg": false,
    "image_path": null,
    "is_available": true
  },
  {
    "id": "veg-thali",
    "category_id": "thali",
    "slug": "veg-thali",
    "name": "Veg Thali",
    "description": "3 Sabzi + 4 Roti + Rice + Salad + Achar + Sweet",
    "base_price": 120,
    "is_veg": true,
    "image_path": null,
    "is_available": true
  }
];
